### ISSUE TITLE
Windows Deployment Test

### ISSUE THREAD

**Issue by JonasSchaub** [zielesny/MIPET#1]
- Installer .exe does not have the version in its name
- default installation folder name contains space
- make it more clear in the tutorial that Tinker needs to be installed separately after completing the installer .exe installation
- Even with admin rights, the properties file cannot be edited in the program files directory

**Comment by JonasSchaub** [comment]
path to the scratch dir must contains slashes, not backslashes. If you copy the path from file explorer in Win, it will contain backslashes by default.

**Comment by JonasSchaub** [comment]
After start-up, the software seems to run but there is no console output at all. A user asks themselves "is sth happening or not?"

**Comment by JonasSchaub** [comment]
Suggestions for the tutorial installation instructions: 
- "Once MIPET is installed successfully, proceed with the installation of [Tinker](https://github.com/zielesny/MIPET/blob/main/Tutorial/Tutorial.md#tinker) by following the provided instructions" ... *below*.
- "...within the MIPET.properties file, which can(*?*) be located in the MIPET root directory." - not *is*?
- Tinker installation instructions could still be more extensive. E.g. explicit note that executables and the full distribution need to be downloaded separately and the latter one only for the parameter files. Also more explicit would be a note like "After unpacking, copy/move the OS-specific Tinker executables into the "tinker" subfolder of your MIPET root directory. Also copy/move the parameter files from the "parameter" subfolder of the full Tinker distribution into the "parameter" folder in the "tinker" folder of your MIPET root directory." And then the example directory structure.
- "Subsequently, double-click on the "MIPET.bat" batch file." - you could add sth here like "... to start the initial test job (see above)"

**Comment by JonasSchaub** [comment]
The initial test job completed successfully and only took about 10 min on my machine.

**Comment by FelixBaensch** [comment]
@JonasSchaub please review again and let me know if it becomes more clear.

**Comment by JonasSchaub** [comment]
> @JonasSchaub please review again and let me know if it becomes more clear.

@FelixBaensch seems like you have implemented all my suggestions perfectly, thank you!
